RabbitMQ and Metrics
StackStorm/puppet-st2 pull request #349
Opened 2022-04-27 14:09 UTC by bishopbm1

Added Metrics configuration options to to setup and configure metrics endpoint needed for metrics collection. Will be using this and adding documentation on setting up Prometheus.

RabbitMQ and erlang changes the repository styles so added some configuration options so if they change again we can more easily update. PackageCloud documentation:
https://packagecloud.io/rabbitmq/erlang/install#bash-rpm
https://packagecloud.io/install/repositories/rabbitmq/erlang/config_file.repo?os=rhel&dist=8&source=script

Relies on the folllowing PR for additional fixes:
https://github.com/voxpupuli/puppet-rabbitmq/pull/907
While waiting for that to be merged this repo and branch can be used:
https://github.com/EncoreTechnologies/puppet-rabbitmq/tree/feature/fix-yum-repo
This repo and branch will remain until the PR is merged.

Error:
```
Error: Execution of '/usr/bin/dnf -d 0 -e 1 -y install rabbitmq-server' returned 1: Importing GPG key 0x4D206F89:
 Userid     : "https://packagecloud.io/rabbitmq/rabbitmq-server (https://packagecloud.io/docs#gpg_signing) <support@packagecloud.io>"
 Fingerprint: 8C69 5B02 19AF DEB0 4A05 8ED8 F4E7 8920 4D20 6F89
 From       : https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
Error: Failed to download metadata for repo 'rabbitmq_erlang': repomd.xml GPG signature verification error: Bad GPG signature
Error: /Stage[main]/Rabbitmq::Install/Package[rabbitmq-server]/ensure: change from 'purged' to 'present' failed: Execution of '/usr/bin/dnf -d 0 -e 1 -y install rabbitmq-server' returned 1: Importing GPG key 0x4D206F89:
 Userid     : "https://packagecloud.io/rabbitmq/rabbitmq-server (https://packagecloud.io/docs#gpg_signing) <support@packagecloud.io>"
 Fingerprint: 8C69 5B02 19AF DEB0 4A05 8ED8 F4E7 8920 4D20 6F89
 From       : https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
Error: Failed to download metadata for repo 'rabbitmq_erlang': repomd.xml GPG signature verification error: Bad GPG signature
```

2022-05-04 09:26 UTC, rush-skills requested changes
Looks good overall, had a few minor nitpicks, added them to the review

2022-05-04 09:26 UTC, rush-skills commented on manifests/profile/server.pp
> +  ## Metrics Settings
Instead of making this part of `profile/server.pp`, can we extract it out to another component, say `server/monitoring.pp`?

2022-05-04 09:26 UTC, rush-skills commented on test/integration/stackstorm/controls/services_test.rb
> +    its('addresses') { should include '0.0.0.0' }
Any reasons for changing these (and not for stream)? 

If there is nginx running, I think it should be expected to be bound to `0.0.0.0` instead, proxying for the st2{api,auth,stream} services running on `127.0.0.1`

2022-05-11 10:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/StackStorm/puppet-st2?pullRequest=349) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/StackStorm/puppet-st2?pullRequest=349) before we can accept your contribution.<br/>**0** out of **3** committers have signed the CLA.<br/><br/>:x: Bradley Bishop<br/>:x: bishopbm1<br/>:x: asktheaxis<br/><hr/>**Bradley Bishop** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/StackStorm/puppet-st2?pullRequest=349) it.</sub>

2022-05-20 01:19 UTC, bishopbm1 commented
@rush-skills Fixed all the test issues. the only failure there is it looks like there might be a problem with the redis repo. its giving random failures downloading it. Was happening in my st2 repo also. I agree with your comment about metrics and will get those changes in tonight.

2022-05-20 21:22 UTC, closed without merging